### ISSUE TITLE
Link target _blank

### ISSUE THREAD

**Issue by jurrid** [editor-js/paragraph#18]
In the editor there is no option te set a inline link to target _blank. Is this something which is on the roadmap?

**Comment by neSpecc** [comment]
This issue would better to transfer to the [Editor.js Core repo](http://github.com/codex-team/editor.js)

**Comment by trinhtam** [comment]
[https://github.com/trinhtam/editorjs-hyperlink ](url) my package. Add url with target & rel attribute

**Comment by mikhail-monchak** [comment]
> [editorjs-hyperlink](https://github.com/trinhtam/editorjs-hyperlink) my package. Add url with target & rel attribute

appreciate the great job and friendly support! thanks

**Comment by trinhtam** [comment]
> > [editorjs-hyperlink](https://github.com/trinhtam/editorjs-hyperlink) my package. Add url with target & rel attribute
> 
> appreciate the great job and friendly support! thanks

Okey thank you

**Comment by talyguryn** [comment]
> [editorjs-hyperlink](https://github.com/trinhtam/editorjs-hyperlink) my package. Add url with target & rel attribute

Good job @trinhtam. I have mention your package in [awesome-editorjs](https://github.com/editor-js/awesome-editorjs) list.

**Comment by trinhtam** [comment]
> > [editorjs-hyperlink](https://github.com/trinhtam/editorjs-hyperlink) my package. Add url with target & rel attribute
> 
> Good job @trinhtam. I have mention your package in [awesome-editorjs](https://github.com/editor-js/awesome-editorjs) list.

Thank you very good

**Comment by calrloco** [comment]
thank you  @trinhtam !!!!

**Comment by philipaarseth** [comment]
Any chance this could be implemented still? 
While the editor-hyperlink package looks nice, I somehow doubt that non-techies know that target blank means open link in new tab.

**Comment by or4** [comment]
hi, you should process paragraph data block in json before save to store

const processAHref = (text = ''): string => {
  const el = document.createElement('div')
  el.innerHTML = text

  for (let i = 0; i < el.childNodes.length; i++) {
    const child = el.childNodes.item(i) as HTMLElement

    const nodeName = getNodeName(child)
    if (nodeName !== 'a') {
      continue
    }
    const att = child.getAttribute('target')
    if (att) {
      continue
    }

    child.setAttribute('target', '_blank')
  }

  return el.innerHTML
}
export const getNodeName = (el: HTMLElement): string => {
  return (el.nodeName || '').toLocaleLowerCase()
}

**Comment by gilluminate** [comment]
Slightly cleaner JS solution for modern browsers

```
export const blankTargetAllLinks = (body: string): string => {
  const html = document.createElement('div');
  html.innerHTML = body;
  const links = html.getElementsByTagName('a');
  for (let i = 0, len = links.length; i < len; i += 1) {
    links[i].target = '_blank';
    links[i].rel = 'noopener noreferrer';
  }
  return html.innerHTML;
};
```
