### ISSUE TITLE
Add a new field for the `data` object in paragraph named: `dir`

### ISSUE THREAD

**Issue by alirezakay** [editor-js/paragraph#43]
Hi,
I have a request for a new feature.

I'm using on a project and I need to handle multilingual texts, both rtl and ltr ones.
I dynamically change the `direction` style of a paragraph and that's not big of a deal.
But I'm currently coping with how to save the **direction** to the data object so that I can save the whole data including the direction of each paragraph.

It's good if we could have sth like this: `{dir:  "ltr | rtl"}`

```
...
      {
         "type": "paragraph",
         "data": {
            "text": "This is an rtl text",
            "dir": "rtl"
         }
      },
      {
         "type": "paragraph",
         "data": {
            "text": "Just an ltr text"
         }
      },
...
```

**Comment by or2008** [comment]
@alirezakay +1
how do you dynamically change the direction style of a paragraph?

**Comment by alirezakay** [comment]
> @alirezakay +1
> how do you dynamically change the direction style of a paragraph?

In the onChange event handler of the Editor:

```js
  const onChange = (api) => {
    const currIdx = api.blocks.getCurrentBlockIndex();
    const currBlock = api.blocks.getBlockByIndex(currIdx);
    if (currBlock) {
      const { innerText } = currBlock.holder;
      currBlock.holder.style.direction = getDir(innerText);
    }
  }
```

**Comment by orbachar** [comment]
@alirezakay Amazing! I didn't know you can get current block index from Editorjs, that what I was missing

thanks for sharing this clean code.

P.S 
here is the stackoverflow URL 
https://stackoverflow.com/questions/12006095/javascript-how-to-check-if-character-is-rtl
