### ISSUE TITLE
Change font size and font family for selected text (feature request)

### ISSUE THREAD

**Issue by ryaltoTom** [editor-js/paragraph#72]
Is there a plugin that allows the user to change the font size and font-family of selected text?

I have looked at https://www.npmjs.com/package/editorjs-inline-font-size-tool and https://github.com/codinova-tech/editorjs-inline-font-family but I can't get it to work and it looks like it's not been looked at in quite a while.

**Comment by neSpecc** [comment]
This can be implemented by creating a Block Tune. It's better to create a discussion in Editor.js Repo: https://github.com/codex-team/editor.js/discussions
