### ISSUE TITLE
Typescript not resolving types

### ISSUE THREAD

**Issue by josstn** [editor-js/paragraph#90]
When importing @editorjs/paragraph in a typescript project with modern settings (package.json type=module, tsconfig moduleResolution=bundler), it does not resolve the typings for Paragraph.

I get error **TS7016: Could not find a declaration file for module @editorjs/paragraph.**

Further it says:
_There are types at node_modules/@editorjs/paragraph/dist/index.d.ts, but this result could not be resolved when respecting package.json exports. The @editorjs/paragraph library may need to update its package.json or typings._

More explanations and solution at this site: https://www.kravchyk.com/typescript-npm-package-json-exports/

One can also check the package here: https://arethetypeswrong.github.io/?p=%40editorjs%2Fparagraph%402.11.6

**Comment by BBugHouse** [comment]
same issue

**Comment by Koffer0-0** [comment]
I had also updated recently from "vite": "4.3.4" to "^4.5.3", "vue-tsc": "^1.8.11" to "vue-tsc": "^2.1.4", because of npm vulnerabilities, and I made "audit fix --force" and after that, it broke down.

**Comment by LloydRivers** [comment]
They're not being exported from the package.json
